In [3]:
from sklearn.model_selection import train_test_split
import numpy as np

In [19]:
# create fake data
fakedata = np.tile(np.array([1,2,3,4]),(10,1)) + np.tile(10*np.arange(1,11),(4,1)).T
fakelabels = np.arange(10)>4

In [26]:
# 3 parts of data: test, devset and test
partitions = [0.8, 0.1, 0.1] 

train_data, test_TMP_data, train_labels, test_TMP_labels = train_test_split(fakedata, fakelabels, train_size=partitions[0])

# we want 80%, 10% and 10%
# currently we've 80%-20% cut from above line
# now we want to split 20% into 10%-10% means in 2 equal halves i.e. 50%-50%
# but partitions[1] is 0.1 i.e. 10%
# so, we're finding out how much is partitions[1] of partitions[1]+partition[2]
split = partitions[1]/sum(partitions[1:]) # it'll give 0.5

devset_data, test_data, devset_labels, test_labels = train_test_split(test_TMP_data, test_TMP_labels, train_size=split)

print(train_data)
print(' ')
print(devset_data)
print(' ')
print(test_data)

# after this we can use dataLoader to bind data with their respective labels


[[ 11  12  13  14]
 [ 31  32  33  34]
 [ 81  82  83  84]
 [101 102 103 104]
 [ 71  72  73  74]
 [ 61  62  63  64]
 [ 91  92  93  94]
 [ 21  22  23  24]]
 
[[41 42 43 44]]
 
[[51 52 53 54]]
